server:
  servlet:
    context-path: /position-mgmt

spring:
  application:
    name: position-mgmt
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:h2/schema.sql
    url: jdbc:h2:mem:pm
    username: sa
    password: sa

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-enums-package: com.celnet.interview.position.mgmt.common.constant